version: '3.8'

services:
 notes:
  build:
   context: .
  ports:
   - 8000:8000
  environment:
   - SERVER_PORT=8000
   - DATABASE_CONNECTIONSTRING=mongodb://localhost:27017/snake-game
  volumes:
   - ./:/code
  command: node app.js

 mongo:
  image: mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config:
